### ISSUE TITLE
meta.hook doesn't check function's return type

### ISSUE THREAD

**Issue by payet-s** [LionelAuroux/pyrser#7]
A meta.hook as said in lessons has to return a boolean value which tells if the function succeeded or not. But when forgetting the return value it sometimes complains sometimes not, and it's really annoying.

I know for sure, it's possible to check the return type and if it isn't a boolean an Exception or a Warning should be raised to warn the user. Obviously, it will help debugging projects when the return statement was forgotten in the meta.hook'd function.

Cordially, payet_s.

**Comment by LionelAuroux** [comment]
Now an exception is send...
